### ISSUE TITLE
Unusual bounded queue semantics

### ISSUE THREAD

**Issue by mafr** [tnm/qr#2]
When a queue is full, push removes entries from the top of the queue which probably isn't what users expect. I think the newest entries should be dropped instead of the old ones. Consumers can still drop entries from the top of the queue if they are considered too old (which may happen for very large queue lengths).

**Comment by tnm** [comment]
As the queue is implemented now, a new element will result in the removal of the oldest element, preserving first in, first out ordering. The stack class implements the kind of structure you are referring to, where the addition of a new element will result in the removal of the last in element, preserving LIFO. This is in line with the classical behavior for queues and stacks.

**Comment by mafr** [comment]
That's not what I meant, sorry for not explaining this properly. A queue is of course a FIFO structure. However, if the queue is _full_, then new entries should no longer be accepted. The implementation currently drops old data on push, and that's something I have never seen in any queuing implementation. Producers should never remove data from the queue that has already been accepted by the queue. Removing accepted entries is the job of consumers.

I realize that this isn't trivial to implement with Redis :)

**Comment by tnm** [comment]
Thanks for the clarification :) This unique type of bounded queue was designed to match with a use case that I've increasingly seen in the wild with Redis - the automatic popping of oldest elements. But your point is valid -what I'm going to do is add in a user-specified argument for the preferred behavior, defaulting to the safer option.

**Comment by tnm** [comment]
Added in user-set option for auto-pop
