### ISSUE TITLE
How to specify the host and port for qr?

### ISSUE THREAD

**Issue by totic** [tnm/qr#8]
Hi, love your library, but dont know how to specify the host and port at init, it would be helpful if you add it to your README, thanks

**Comment by jacinda** [comment]
I'm sure you've figured this out by now, but any keyword arguments passed at initialization are used when creating the redis connection object, so 

```
my_queue = Queue('my_key', host='localhost', port=9876) 
```

will do the trick.

**Comment by tnm** [comment]
Added docs here: https://github.com/tnm/qr/commit/76d44cc911e0e6abf8cec98f2837e1b577e680bb
